/*
* Generated by XIV.Core.Utils.ClassGenerator
*/
public static class AudioMixerConstants 
{
	// Inner Classes
	public static class DefaultMixer 
	{
		// Inner Classes
		public static class Parameters 
		{
			// Members
			public const string EffectsVolume = "EffectsVolume";
			public const string MasterVolume = "MasterVolume";
			public const string MusicVolume = "MusicVolume";
			public static readonly string[] All = 
			{
				EffectsVolume,
				MasterVolume,
				MusicVolume,
			};
			
		} // class Parameters
		 
		public static class MixerGroups 
		{
			// Members
			public static readonly string Master = "Master";
			public static readonly string Effects = "Effects";
			public static readonly string Musics = "Musics";
			public static readonly string[] All = 
			{
				Master,
				Effects,
				Musics,
			};
			
		} // class MixerGroups
		 
		
	} // class DefaultMixer
	 
	
} // class AudioMixerConstants
 

