/*
* Generated by XIV.Core.Utils.ClassGenerator
*/
using UnityEngine;

public static class PhysicsConstants 
{
	// Members
	public const string Default = "Default";
	public static readonly int DefaultLayer = LayerMask.NameToLayer("Default");
	public const string TransparentFX = "TransparentFX";
	public static readonly int TransparentFXLayer = LayerMask.NameToLayer("TransparentFX");
	public const string Ignore_Raycast = "Ignore Raycast";
	public static readonly int Ignore_RaycastLayer = LayerMask.NameToLayer("Ignore Raycast");
	public const string Water = "Water";
	public static readonly int WaterLayer = LayerMask.NameToLayer("Water");
	public const string UI = "UI";
	public static readonly int UILayer = LayerMask.NameToLayer("UI");
	public const string Rope = "Rope";
	public static readonly int RopeLayer = LayerMask.NameToLayer("Rope");
	public const string Ground = "Ground";
	public static readonly int GroundLayer = LayerMask.NameToLayer("Ground");
	public const string Player = "Player";
	public static readonly int PlayerLayer = LayerMask.NameToLayer("Player");
	public const string Lava = "Lava";
	public static readonly int LavaLayer = LayerMask.NameToLayer("Lava");
	public const string Hazzard = "Hazzard";
	public static readonly int HazzardLayer = LayerMask.NameToLayer("Hazzard");
	public const string EndGate = "EndGate";
	public static readonly int EndGateLayer = LayerMask.NameToLayer("EndGate");
	public const string Persistant = "Persistant";
	public static readonly int PersistantLayer = LayerMask.NameToLayer("Persistant");
	public const string PostProcess = "PostProcess";
	public static readonly int PostProcessLayer = LayerMask.NameToLayer("PostProcess");
	public const string Enemy = "Enemy";
	public static readonly int EnemyLayer = LayerMask.NameToLayer("Enemy");
	public const string Collectable = "Collectable";
	public static readonly int CollectableLayer = LayerMask.NameToLayer("Collectable");
	public const string Interactable = "Interactable";
	public static readonly int InteractableLayer = LayerMask.NameToLayer("Interactable");
	
} // class PhysicsConstants
 

